//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN_XLV_MilosPeric
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct
    {
        public Nullable<bool> InStock { get; set; }
        public string Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public int ID { get; set; }
    }
}
